name: Call Scheduler

on:
  schedule:
    - cron: "0 0 * * *" # 하루에 한번 실행

jobs:
  call-schedular-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install axios

      - name: Send POST request with API key
        run: |
          node -e "
          const axios = require('axios');
          axios.post('https://mitaly.vercel.app/api/scheduler', {
            'api-key': process.env.API_KEY
          }).then(response => {
            console.log('Response:', response.data);
          }).catch(error => {
            console.log('Error:', error.response ? error.response.data : error.message);
          });
          "
        env:
          API_KEY: ${{ secrets.SCHEDULER_API_KEY }}
